### ISSUE TITLE
Clarify intent of <author> @initials

### ISSUE THREAD

**Issue by ronaldtse** [hlflanagan/draft-flanagan-7322bis#4]
This was originally from https://github.com/reschke/xml2rfc/issues/14 .

Currently `rfc2629.xslt` warns if the author initials are listed as "`A`" instead of "`A.`". This applies to the `<author>` tag which appears both in `<rfc><front>` and `<references><front>`.

https://tools.ietf.org/html/draft-flanagan-7322bis-02#section-4.1.1

Would it be possible to clarify the desired format of `initials`? Some of the more interesting ones I've seen are "A. B.", "A-B."

cc: @reschke

**Comment by reschke** [comment]
Note it is `rfc2629.xslt`, not `xml2rfc`...

**Comment by ronaldtse** [comment]
OOPS... @reschke is right. Let me correct it.

**Comment by ronaldtse** [comment]
@hlflanagan any thoughts on this? We're looking forward to resolving it for https://github.com/reschke/xml2rfc/issues/14. Thanks!

cc: @opoudjis

**Comment by hlflanagan** [comment]
It should be "A. B." This is pure CMOS, so I don't think it needs to go in the RFC Style Guide. We mostly cover what makes us special snowflakes.

**Comment by ronaldtse** [comment]
@hlflanagan thanks for the clarification! Not to be pedantic, but APA has also specified some rules for more complex surnames in citation. 

Are these allowed as well?

Name | Initials in RFC XML
-- | -- 
Delta Gamma. Alpha-Beta | D. A-B.
Delta Alpha Beta | D. AB.
Delta von Alpha Beta | D. vAB.
Delta de Alpha | D. dA.
Delta G. St. Alpha | D. SA.
Delta G. Alpha II | D. A. II

(In the table, surnames start with "Alpha")
